name: PlayerLogger

version: 2.8

description: Logs player events.

author: McLuke300

main: me.mcluke300.playerlogger.playerlogger

commands:
   Playerlogger:
      description: Playerlogger commands