name: PlayerLogger
version: ${plugin.version}
description: Logs player events.
api-version: ${spigot.api.version}
author: McLuke300, add5tar
main: me.mcluke300.playerlogger.PlayerLogger

loadbefore: [PwnFilter, CommandHelper]

commands:
   playerlogger:
      description: Playerlogger commands

permissions:
  playerlogger.admin:
      description: Full access to all commands (admin)
